-- | translating CoreFn generated by purs compiler ECF.
-- | Large part of this module is triival translating functions.
module Purvasm.MiddleEnd.ECF.Translate where

import Prelude

import PureScript.CoreFn as CF
import Purvasm.MiddleEnd.ECF.Syntax (Expr(..))
import Purvasm.Types (Ident(..))

type CorefnExpr = CF.Expr CF.Ann

translateExpr :: CorefnExpr -> Expr Unit
translateExpr = case _ of
  _ -> ExprVar unit (Ident "x")
